First iteration
OlegShamkeev/go_final_project pull request #1
Opened 2024-05-21 19:09 UTC by OlegShamkeev

2024-05-22 09:30 UTC, dirtymew requested changes
Привет Олег

хорошая работа - есть что поправить

для первой итерации ревью пока достаточно см комментарии к PR - иначе сильно ревью затянется.

2024-05-22 09:30 UTC, dirtymew commented on README.md
> +- добавлена возможность создания Docker image (для данной опции необходимо иметь в директории с файлом Dockerfile скомпилированный исполняемый файл, подходящий для запуска в ОС Linux);
тут нужно подробнее описать как это сделать

вообще можно и докером собрать бинарник - и все будет красиво 

см комментарий в Dockerfile

2024-05-22 09:30 UTC, dirtymew commented on Dockerfile
> +COPY finaltask ./
сейчас докерфайл не рабочий так как нет finaltask в репозитории

тут можно разными путями пойти - плохой путь хранить бинарник в репозитории

можно сделать несколько этапо в докер  - на первом этапе осуществляется сборка бинариника и потом он копируется в  финальный образ...

2024-05-22 09:30 UTC, dirtymew commented on README.md
> +- url для доступа - **http://localhost** (с учётом порта).
можно еще добавить описание про то как тесты запустить

2024-05-22 09:30 UTC, dirtymew commented on main.go
> +	log.Printf("Starting web-server on port: %d\n", cfg.Port)
отлично что добавил сообщение о запуске сервера

2024-05-22 09:30 UTC, dirtymew commented on helper.go
> +	d, err := time.Parse("20060102", date)
20060102 - мб в константу перенести

2024-05-22 09:30 UTC, dirtymew commented on helper.go
> +func validateAndUpdateTask(task *Task, update bool) *Result {
мб это функции структуры Task

2024-05-22 09:30 UTC, dirtymew commented on handler.go
> +	w.Write(res)
на 38 строке обработал ошибку а тут почему нет?

2024-05-22 09:30 UTC, dirtymew commented on handler.go
> +		return
а что будет если err == nil - или логируй ошибку или убирай лишнее условие

2024-05-22 09:30 UTC, dirtymew commented on db.go
> +			// err = f.Chmod(0666)
лишние коментарии стоит убрать

2024-05-22 09:30 UTC, dirtymew commented on db.go
> +	log.Printf("Insert new record in DB:\n date: %s, title: %s, comment: %s, repeat: %s\n", task.Date, task.Title, task.Comment, task.Repeat)
это прям не очень

лог пишется на каждый запрос - я понимаю что в курсе не было про логирование  - но так не делают

есть понятие уровень логирования - для уровней Trace и Debug это ок - но в обычном режиме работы приложения это слишком дорого столько в std out писать

2024-05-22 09:30 UTC, dirtymew commented on db.go
> +	log.Printf("Insert new record in DB:\n date: %s, title: %s, comment: %s, repeat: %s\n", task.Date, task.Title, task.Comment, task.Repeat)
я бы преложил тут сделать только логирование ошибок

2024-05-22 09:30 UTC, dirtymew commented on db.go
> +	if len(search) > 0 {
лучше switch - по возможности не используй else  - получается "лапша" - очень сложно дебажить и поддерживать такой код

2024-05-22 09:30 UTC, dirtymew commented on db.go
> +	selectRow := `SELECT * FROM scheduler WHERE id = ?`
лучше явно указывать поля в select

2024-05-23 15:17 UTC, OlegShamkeev commented on main.go
> +	log.Printf("Starting web-server on port: %d\n", cfg.Port)
Привет. Спасибо за комментарий

2024-05-23 15:21 UTC, OlegShamkeev commented on helper.go
> +	d, err := time.Parse("20060102", date)
Сделано

2024-05-23 15:23 UTC, OlegShamkeev commented on handler.go
> +		return
Исправлено

2024-05-23 15:30 UTC, OlegShamkeev commented on handler.go
> +	w.Write(res)
Решил не перегружать код проверками ошибок маршаллинга относительно простой структуры, которую создаем на лету

2024-05-23 15:31 UTC, OlegShamkeev commented on handler.go
> +	w.Write(res)
Или вопрос про 80ую строчку?

2024-05-23 15:31 UTC, OlegShamkeev commented on helper.go
> +func validateAndUpdateTask(task *Task, update bool) *Result {
Исправил

2024-05-23 15:42 UTC, OlegShamkeev commented on db.go
> +			// err = f.Chmod(0666)
Исправлено

2024-05-23 15:43 UTC, OlegShamkeev commented on db.go
> +	log.Printf("Insert new record in DB:\n date: %s, title: %s, comment: %s, repeat: %s\n", task.Date, task.Title, task.Comment, task.Repeat)
Исправлено

2024-05-23 15:53 UTC, OlegShamkeev commented on db.go
> +	if len(search) > 0 {
Исправлено

2024-05-23 16:01 UTC, OlegShamkeev commented on db.go
> +	selectRow := `SELECT * FROM scheduler WHERE id = ?`
Почему именно в select явно указывать, а в других - нет? Не пошёл путем NamedQuery, т.к. показалось overhead для простых запросов. Т.к. до этого нужно создавать мапу для sqlx...

2024-05-23 17:21 UTC, OlegShamkeev commented on Dockerfile
> +COPY finaltask ./
Попробовал сделать через файл скрипта

2024-05-23 17:21 UTC, OlegShamkeev commented on README.md
> +- url для доступа - **http://localhost** (с учётом порта).
Исправил

2024-05-24 18:21 UTC, dirtymew approved these changes
Привет Олег

Работу принимаю - критических замечаний нет

есть конечно что улучшить - в особенности в дизайне и архитектуре ...

но это уже на будущее

Удачи

2024-05-24 18:21 UTC, dirtymew commented on Dockerfile
> +COPY finaltask ./
так можно - но не очень хорошо

нужно поддерживать будет скрипт и докерфайл... 

на будущее посмотри https://docs.docker.com/build/building/multi-stage/

2024-05-24 18:21 UTC, dirtymew commented on handler.go
> +	w.Write(res)
нет про 81 

_ , _ = w.Write(resp)

тут нужно либо явно проигнорировать ошибку или ее логировать

хорошие линтеры на это ругаться будут

2024-05-24 18:21 UTC, dirtymew commented on handler.go
> +		return
нет... когда w.Write вывалится в ошибку то тогда уже http.Error не поможет... 
так что тут менять ответ бесполезно

а просто в хотябы в stdout написать можно

2024-05-24 18:21 UTC, dirtymew commented on db.go
> +	selectRow := `SELECT * FROM scheduler WHERE id = ?`
а в других SQL запросах нет *-чек )

тут дискуссионный конечно вопрос... 

не сразу заметил что ты sqlx используешь - тогда ок но надо поля структуры проаннотировать `db:"`

2024-05-24 20:26 UTC, OlegShamkeev commented
> Привет Олег
> 
> Работу принимаю - критических замечаний нет
> 
> есть конечно что улучшить - в особенности в дизайне и архитектуре ...
> 
> но это уже на будущее
> 
> Удачи

Антон, привет. 

Спасибо за фидбек и за замечания. Но я не согласен в фидбеке с одним важным моментом. 
Ты пишешь, что что-то не так в дизайне и архитектуре. Но что именно, не указываешь. Также не указываешь, куда можно пойти, почитать, посмотреть, чтобы в этом разобраться. 
Это учебный итоговый проект, и для меня как никогда важна обратная связь про структуру приложения, про основу.  И построение приложения очень сильно зависит от верной структуры. На курсе нам про это вообще ничего не дали. Здесь я попробовал реализовать то, как вижу, и получаю фидбек, что не так. А что именно - где-то там в будущем. 
Давай исправим этот момент?

2024-05-24 20:27 UTC, OlegShamkeev commented on handler.go
> +	w.Write(res)
Спасибо

2024-05-24 20:28 UTC, OlegShamkeev commented on Dockerfile
> +COPY finaltask ./
Спасибо, интересно, изучу

2024-05-24 20:29 UTC, OlegShamkeev commented on handler.go
> +		return
Понял, спасибо

2024-05-24 20:54 UTC, dirtymew commented
Олег конечно с радостью помогу...

Дай мне время я подготовлю подробный комментарий.

Для начала можно начать с вот этой статьи - там в основном про организацию проекта, но косвенно может навести на дизайн  https://github.com/golang-standards/project-layout

2024-05-24 22:29 UTC, dirtymew commented
> Олег конечно с радостью помогу...
> 
> Дай мне время я подготовлю подробный комментарий.
> 
> Для начала можно начать с вот этой статьи - там в основном про организацию проекта, но косвенно может навести на дизайн https://github.com/golang-standards/project-layout

Архитектура и дизайн а также логирование, работа с ошибками и много других важных тем не рассматриваются в рамках базового курса к сожалению.  Но в процессе прохождения конечно были "намеки" на это - я не знаю что было в вебинарах итд но вот в заданиях про api и посылки там можно подсмотреть подходы...  это тема сложная - есть множество подходов и теории на этот счет требующих как и фундаментальных знаний так и практики.

Для более глубоко изучения рекомендую
 - https://github.com/golang-standards/project-layout
 - https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html
 - https://github.com/go-kit/kit

Также общие вещи и не относятся к конкретному языку программирования
 - https://medium.com/geekculture/solid-dry-kiss-yagni-engineering-principles-c1e73610db4c
 - https://refactoring.guru/ru/design-patterns/what-is-pattern

по заданию 
Как бы я разделил компоненты и зоны ответственности

<img width="1315" alt="image" src="https://github.com/OlegShamkeev/go_final_project/assets/8639955/ae68b13a-57a8-4382-8f51-e1cf0a62ce7d">


@OlegShamkeev если есть желание то можешь попробовать переделать 
я не могу гарантировать что быстро буду отвечать, но ревью сделаю и отвечу на конкретные вопросы

в целом не должно быть проблем натянуть на https://github.com/golang-standards/project-layout

2024-05-25 06:35 UTC, OlegShamkeev commented
> > Олег конечно с радостью помогу...
> > Дай мне время я подготовлю подробный комментарий.
> > Для начала можно начать с вот этой статьи - там в основном про организацию проекта, но косвенно может навести на дизайн https://github.com/golang-standards/project-layout
> 
> Архитектура и дизайн а также логирование, работа с ошибками и много других важных тем не рассматриваются в рамках базового курса к сожалению. Но в процессе прохождения конечно были "намеки" на это - я не знаю что было в вебинарах итд но вот в заданиях про api и посылки там можно подсмотреть подходы... это тема сложная - есть множество подходов и теории на этот счет требующих как и фундаментальных знаний так и практики.
> 
> Для более глубоко изучения рекомендую
> 
> * https://github.com/golang-standards/project-layout
> * https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html
> * https://github.com/go-kit/kit
> 
> Также общие вещи и не относятся к конкретному языку программирования
> 
> * https://medium.com/geekculture/solid-dry-kiss-yagni-engineering-principles-c1e73610db4c
> * https://refactoring.guru/ru/design-patterns/what-is-pattern
> 
> по заданию Как бы я разделил компоненты и зоны ответственности
> 
> <img alt="image" width="1315" src="https://private-user-images.githubusercontent.com/8639955/333747153-ae68b13a-57a8-4382-8f51-e1cf0a62ce7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MTkxMjcsIm5iZiI6MTcxNjYxODgyNywicGF0aCI6Ii84NjM5OTU1LzMzMzc0NzE1My1hZTY4YjEzYS01N2E4LTQzODItOGY1MS1lMWNmMGE2MmNlN2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjVUMDYzMzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTBjZTNkMjA4MGViZTE5OTA1Zjc3Y2E2MDA4MmRiMzM2ODNlYjJkY2Q1NjdiZDY3OTIwMGQ0ZTcwMmVhYjI0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jBhCR1oyvpWfEjQyFTDQd2fjQNQANQoJGnrkAybxq6o">
> @OlegShamkeev если есть желание то можешь попробовать переделать я не могу гарантировать что быстро буду отвечать, но ревью сделаю и отвечу на конкретные вопросы
> 
> в целом не должно быть проблем натянуть на https://github.com/golang-standards/project-layout

Спасибо большое за ответ! Вникну и попробую переделать.

2024-05-25 10:11 UTC, dirtymew commented
> 1. После итогового проекта я планировал как в раз тщательно изучить книгу Джона Боднера "Го: идиомы и паттерны проектирования". Очень много хороших отзывов на эту книгу я встречал. Я же правильно понимаю, что знания в ней как в раз помогут закрыть пробелы как в раз по этой теме?

Не читал - но по содержанию как будто-бы тоже самое что было в курсе мб чуть глубже...

> 2. Если действовать дальше, то я вижу это так. Этот PR я мержу в основную ветку, затем оттуда делаю новую, где пробую все переделать по красоте. Как дальше на новый PR мне тебе маякнуть (сейчас не получится отправить ссылку), чтобы (по возможности, конечно) ты смог посмотреть и дать обратную связь?

Да можно и так - теги потом меня @OlegShamkeev

2024-06-16 14:33 UTC, merged