Second iteration
OlegShamkeev/go_final_project pull request #2
Opened 2024-07-08 06:36 UTC by OlegShamkeev

Code refactor according go-standard layout

2024-07-08 06:44 UTC, OlegShamkeev commented on build.sh
> +docker run --rm -v "$PWD":/app -w /app -e GOOS=linux -e GOARCH=arm64 -e CGO_ENABLED=1 golang:1.22 go build -o ./finaltask ./cmd/final-project/
Вот здесь файл не переделывал на многоуровневую сборку в Docker. Но у меня вопрос про корректность вызова главного файла main.go в директории cmd. Действительно ли обычно так происходит запуск всей программы, когда она разбита на layout?

2024-07-08 06:45 UTC, OlegShamkeev commented on cmd/final-project/main.go
> +	database.Cfg = &cfg
Корректно ли вот так выполнять injection данных конфигурации в другие модули из main?

2024-07-08 06:48 UTC, OlegShamkeev commented on internal/database/database.go
> +	Db *sqlx.DB
В данном модуле (на мой взгляд) получилось логично выделить в отдельный модуль database, где функции непосредственного обращения к БД выделены в методы к структуре, и есть две независимых функции инициализации структуры.

2024-07-08 06:51 UTC, OlegShamkeev commented on internal/services/nextdateservice.go
>  func NextDate(now time.Time, date string, repeat string, update bool) (string, error) {
Данную функцию вынес в отдельный сервис расчета nextdate. Корректно ли?

2024-07-08 06:52 UTC, OlegShamkeev commented on internal/services/taskservice.go
> +type Task struct {
Вот здесь есть сомнения, что выделил отдельную структуру и ее метод в отдельный сервис работы с task. Корректно ли @dirtymew?

2024-07-08 06:53 UTC, OlegShamkeev commented on internal/types/types.go
> +type Result struct {
Данную структуру не выделил во что-то отдельное и оставил в модуле types. Корректно ли?

2024-07-08 06:54 UTC, OlegShamkeev commented on internal/utils/helper.go
> +func ValidateTaskID(id string) (int, error) {
Здесь мне кажется всё валидным по вынесению данных вспомогательных функций в отдельный модуль. Корректно ли?

2024-07-08 06:55 UTC, OlegShamkeev commented on cmd/final-project/main.go
> +		transport.Secret = secret
Насколько верно генерить secret (для дальнейшего использования в jwt) в main и дальше передавать его в модуль?

2024-07-08 06:59 UTC, OlegShamkeev commented on internal/transport/handler.go
> +
Вот здесь столкнулся со сложностями и нужна помощь @dirtymew, т.к. здесь есть с одной стороны много похожей логики с проверкой разных ошибок и формировании http ответа. Но выделить во что-то одно и вынести в отдельный модуль (каким мог бы быть этот модуль??) пока что не нашел ответа, оставил как есть.

2024-07-08 08:46 UTC, dirtymew requested changes
Привет Олег

ответил на вопросы - так в целом ок выглядит 

внеси правки попробую глубже покопать

2024-07-08 08:46 UTC, dirtymew commented on build.sh
> +docker run --rm -v "$PWD":/app -w /app -e GOOS=linux -e GOARCH=arm64 -e CGO_ENABLED=1 golang:1.22 go build -o ./finaltask ./cmd/final-project/
да это ок 

но в докер я бы брал сразу образ с go причем с go твоего релиза

также у тебя приложение сетевое поэтому нужно прикидывать порты из контейнера

2024-07-08 08:46 UTC, dirtymew commented on cmd/final-project/main.go
> +	database.Cfg = &cfg
да корректно но лучше через конструкторы

типа NewStorage(cfg *config.Config)

2024-07-08 08:46 UTC, dirtymew commented on cmd/final-project/main.go
> +		transport.Secret = secret
для данного задания наверное ок - обычно так аутентификации не делается

лучше сделать такую логику - если Password то используем его если нет то работаем без авторизации вообще

2024-07-08 08:46 UTC, dirtymew commented on internal/services/nextdateservice.go
>  func NextDate(now time.Time, date string, repeat string, update bool) (string, error) {
ну я бы это сервисом не называл 
я бы так рекомендовал 

```
task
     |- task.go

nextdate
     |- nextdate.go
```

2024-07-08 08:46 UTC, dirtymew commented on internal/database/database.go
> +package database
лучше пакет storage назвать

2024-07-08 08:46 UTC, dirtymew commented on internal/database/database.go
> +package database
и мб в пакет task даже положить....

2024-07-08 08:46 UTC, dirtymew commented on internal/database/database.go
> +	Db *sqlx.DB
Да так именно и надо делать

2024-07-08 08:46 UTC, dirtymew commented on internal/services/taskservice.go
> +type Task struct {
ну это не сервис - лучше просто пакет task сделать

а так это ок все верно

2024-07-08 08:46 UTC, dirtymew commented on internal/transport/handler.go
> +
да особо ничего не сделаешь

можно какие-то обертки типо таких добавить
```
func errorJson(w http.ResponseWriter, msg any) {
	writeJson(w, Resp{
		Error: fmt.Sprint(msg),
	})
}

func writeJson(w http.ResponseWriter, data any) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	if err := json.NewEncoder(w).Encode(data); err != nil {
		log.Println(err)
	}
}
```

или я не понял вопрос @OlegShamkeev сформулируй конкретную проблему

2024-07-08 08:46 UTC, dirtymew commented on internal/transport/handler.go
>  		w.Write(res)
_ , _ = w.Write(resp)

тут нужно либо явно проигнорировать ошибку или ее логировать

хорошие линтеры на это ругаться будут и не зря

2024-07-08 08:46 UTC, dirtymew commented on internal/utils/helper.go
> +func ValidateTaskID(id string) (int, error) {
да в целом зачем? если это относится к task то пусть будет рядом с task так логичнее

2024-07-08 08:46 UTC, dirtymew commented on internal/types/types.go
> +type Result struct {
я бы так не делал а положил там где она используется в handlers

2024-07-08 08:46 UTC, dirtymew commented on internal/transport/handler.go
> +package transport
это не совсем транспорт я бы api назвал

2024-07-11 14:22 UTC, OlegShamkeev commented on build.sh
> +docker run --rm -v "$PWD":/app -w /app -e GOOS=linux -e GOARCH=arm64 -e CGO_ENABLED=1 golang:1.22 go build -o ./finaltask ./cmd/final-project/
насчет вызова понял, спасибо. По поводу образа go в докер - не понял... 
По поводу прокидывания портов - я вынес это в вызов самого контейнера из образа. Или лучше прям явно в Dockerfile прописать?

2024-07-11 14:22 UTC, OlegShamkeev commented on cmd/final-project/main.go
> +	database.Cfg = &cfg
Переделал, спасибо за комментарий.

2024-07-11 14:23 UTC, OlegShamkeev commented on internal/database/database.go
> +	Db *sqlx.DB
Спасибо за коммент

2024-07-11 14:23 UTC, OlegShamkeev commented on internal/services/nextdateservice.go
>  func NextDate(now time.Time, date string, repeat string, update bool) (string, error) {
Спасибо за коммент, переделал

2024-07-11 14:23 UTC, OlegShamkeev commented on internal/types/types.go
> +type Result struct {
Спасибо, переделал

2024-07-11 14:24 UTC, OlegShamkeev commented on internal/utils/helper.go
> +func ValidateTaskID(id string) (int, error) {
Спасибо за коммент, переделал

2024-07-11 14:25 UTC, OlegShamkeev commented on cmd/final-project/main.go
> +		transport.Secret = secret
Вынес генерацию секрета на основании наличия password в конструктор модуля api, где соотв и используется он в функции аутентификации

2024-07-11 14:27 UTC, OlegShamkeev commented on internal/database/database.go
> +package database
Переименовал в storage, но в модуль task заносить не стал, оставил отдельным. Выглядит storage целостным решением для своего уровня

2024-07-11 14:29 UTC, OlegShamkeev commented on internal/transport/handler.go
>  		w.Write(res)
Спасибо за комментарий, поправил

2024-07-11 15:15 UTC, OlegShamkeev commented on internal/transport/handler.go
> +
Да, ты прав. Я ранее пробовал писать подобную обертку для повторяющихся ответов об ошибках. Но столкнулся с тем, что в создаваемую функцию не могу передать ссылку на ResponseWriter. Это меня смутило и я не стал передавать копию. Но, видимо, это норм и это сильно упростило чтение кода и сократило его. Спасибо за подсказку

2024-07-11 15:18 UTC, OlegShamkeev commented
Привет, @dirtymew ! 
Спасибо за предыдущие комменты. 
Внес правки на все замечания. Посмотри пожалуйста на них.

2024-07-11 17:31 UTC, dirtymew commented on build.sh
> +docker run --rm -v "$PWD":/app -w /app -e GOOS=linux -e GOARCH=arm64 -e CGO_ENABLED=1 golang:1.22 go build -o ./finaltask ./cmd/final-project/
FROM ubuntu:latest - базовый образ у тебя

лучше взять сразу образ с go твоей версии

2024-07-12 06:34 UTC, OlegShamkeev commented on build.sh
> +docker run --rm -v "$PWD":/app -w /app -e GOOS=linux -e GOARCH=arm64 -e CGO_ENABLED=1 golang:1.22 go build -o ./finaltask ./cmd/final-project/
понял, спасибо

2024-07-12 16:44 UTC, OlegShamkeev commented on build.sh
> +docker run --rm -v "$PWD":/app -w /app -e GOOS=linux -e GOARCH=arm64 -e CGO_ENABLED=1 golang:1.22 go build -o ./finaltask ./cmd/final-project/
@dirtymew Антон, а есть ли еще какие-то моменты, которые ты заметил? Или можно считать, что основной костяк приложения есть и он достаточно хорош?

2024-07-12 17:27 UTC, dirtymew commented on build.sh
> +docker run --rm -v "$PWD":/app -w /app -e GOOS=linux -e GOARCH=arm64 -e CGO_ENABLED=1 golang:1.22 go build -o ./finaltask ./cmd/final-project/
да это и не сильный косяк - лучше конечно максимально легковесные образы делать, но не страшно

2024-07-12 17:29 UTC, dirtymew commented on build.sh
> +docker run --rm -v "$PWD":/app -w /app -e GOOS=linux -e GOARCH=arm64 -e CGO_ENABLED=1 golang:1.22 go build -o ./finaltask ./cmd/final-project/
ну конечно есть куда рости - см https://medium.com/@shershnev/layered-architecture-implementation-in-golang-6318a72c1e10 или https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html

всякие SOLID KISS DRY YAGNI  прочие парадигмы - это все с опытом приходит только

2024-07-13 08:00 UTC, OlegShamkeev commented on build.sh
> +docker run --rm -v "$PWD":/app -w /app -e GOOS=linux -e GOARCH=arm64 -e CGO_ENABLED=1 golang:1.22 go build -o ./finaltask ./cmd/final-project/
@dirtymew Спасибо за ссылки, поизучаю. 
А про конкретно данное приложение в плане структуры - есть ли что-то явно выбивающееся, и что стоило бы поправить? (Если мы опираемся на структуру standard layout)

2024-07-13 09:26 UTC, dirtymew commented on build.sh
> +docker run --rm -v "$PWD":/app -w /app -e GOOS=linux -e GOARCH=arm64 -e CGO_ENABLED=1 golang:1.22 go build -o ./finaltask ./cmd/final-project/
- лайаут можно поправить https://github.com/golang-standards/project-layout
- стоит ввести еще один уровень абстракции между хендерами и сторожем - service
- к абсракциям добавить интерфейсы - например если нужно поменять будет бд то менять нужно будет только реализацию storage
- sh скрипт поменять на  make

2024-07-13 10:44 UTC, OlegShamkeev commented on build.sh
> +docker run --rm -v "$PWD":/app -w /app -e GOOS=linux -e GOARCH=arm64 -e CGO_ENABLED=1 golang:1.22 go build -o ./finaltask ./cmd/final-project/
Понял, спасибо за ревью @dirtymew

2024-07-13 10:44 UTC, merged